from pathlib import Path
import json
from typing import Optional, Sequence, Union

import numpy as np
import torch.nn as nn

from .model import CVAETrainer


def _r_string(value: str) -> str:
    return json.dumps(value)


def _r_vector(values: np.ndarray) -> str:
    flat = np.asarray(values, dtype=np.float64).ravel()
    return "c(" + ", ".join(format(float(value), ".17g") for value in flat) + ")"


def _r_strings(values: Optional[Sequence[str]]) -> str:
    if values is None:
        return "NULL"
    return "c(" + ", ".join(_r_string(value) for value in values) + ")"


def _linear_spec(layer: nn.Linear) -> str:
    weight = layer.weight.detach().cpu().numpy().T
    bias = layer.bias.detach().cpu().numpy()
    return (
        "list(weight = matrix("
        + _r_vector(weight)
        + f", nrow = {weight.shape[0]}L, ncol = {weight.shape[1]}L, byrow = TRUE), "
        + "bias = "
        + _r_vector(bias)
        + ")"
    )


def _validate_names(
    values: Optional[Sequence[str]], expected: int, name: str
) -> Optional[list[str]]:
    if values is None:
        return None
    result = [str(value) for value in values]
    if len(result) != expected:
        raise ValueError(f"{name} must contain exactly {expected} values.")
    if len(set(result)) != len(result):
        raise ValueError(f"{name} must not contain duplicates.")
    return result


def export_bernoulli_r(
    trainer: CVAETrainer,
    output_path: Union[str, Path],
    feature_names: Optional[Sequence[str]] = None,
    outcome_names: Optional[Sequence[str]] = None,
) -> Path:
    """Export a fitted Bernoulli decoder as dependency-free base R source."""
    if not isinstance(trainer, CVAETrainer):
        raise TypeError("trainer must be a CVAETrainer instance.")
    if trainer.outcome_type != "bernoulli":
        raise ValueError("Standalone R export currently supports Bernoulli models only.")
    if not trainer.trained or trainer.x_mean is None or trainer.x_std is None:
        raise RuntimeError("The trainer must be fitted before export.")

    feature_names = _validate_names(feature_names, trainer.x_dim, "feature_names")
    outcome_names = _validate_names(outcome_names, trainer.y_dim, "outcome_names")
    model = trainer.model

    decoder_layers = ",\n    ".join(_linear_spec(layer) for layer in model.dec_layers)
    head_layers = [layer for layer in model.dec_logits_head if isinstance(layer, nn.Linear)]
    if len(head_layers) != 2:
        raise ValueError("Unsupported Bernoulli decoder head architecture.")

    source = f'''# Generated by multioutcome_cvae. This file requires base R only.
.multioutcome_cvae_model <- list(
  format_version = 1L,
  outcome_type = "bernoulli",
  x_dim = {trainer.x_dim}L,
  y_dim = {trainer.y_dim}L,
  latent_dim = {trainer.latent_dim}L,
  feature_names = {_r_strings(feature_names)},
  outcome_names = {_r_strings(outcome_names)},
  x_mean = {_r_vector(trainer.x_mean)},
  x_std = {_r_vector(trainer.x_std)},
  decoder_layers = list(
    {decoder_layers}
  ),
  head_layers = list(
    {_linear_spec(head_layers[0])},
    {_linear_spec(head_layers[1])}
  ),
  skip_layer = {_linear_spec(model.dec_logits_skip)}
)

.cvae_add_bias <- function(value, bias) {{
  sweep(value, 2L, bias, FUN = "+")
}}

.cvae_validate_x <- function(X) {{
  if (!is.matrix(X) && !is.data.frame(X)) {{
    stop("X must be a numeric matrix or data frame.", call. = FALSE)
  }}
  X <- as.matrix(X)
  if (!is.numeric(X)) stop("X must be numeric.", call. = FALSE)
  if (nrow(X) < 1L || ncol(X) != .multioutcome_cvae_model$x_dim) {{
    stop(sprintf("X must have at least one row and exactly %d columns.",
                 .multioutcome_cvae_model$x_dim), call. = FALSE)
  }}
  expected <- .multioutcome_cvae_model$feature_names
  if (!is.null(expected) && !is.null(colnames(X))) {{
    missing_names <- setdiff(expected, colnames(X))
    if (length(missing_names)) {{
      stop(paste("X is missing required features:", paste(missing_names, collapse = ", ")),
           call. = FALSE)
    }}
    X <- X[, expected, drop = FALSE]
  }}
  storage.mode(X) <- "double"
  if (any(!is.finite(X))) stop("X must contain only finite values.", call. = FALSE)
  X
}}

.cvae_standardize_x <- function(X) {{
  X <- .cvae_validate_x(X)
  sweep(sweep(X, 2L, .multioutcome_cvae_model$x_mean, FUN = "-"),
        2L, .multioutcome_cvae_model$x_std, FUN = "/")
}}

cvae_decoder_probabilities <- function(X, Z) {{
  X_std <- .cvae_standardize_x(X)
  Z <- as.matrix(Z)
  if (!is.numeric(Z) || nrow(Z) != nrow(X_std) ||
      ncol(Z) != .multioutcome_cvae_model$latent_dim || any(!is.finite(Z))) {{
    stop(sprintf("Z must be a finite numeric matrix with %d rows and %d columns.",
                 nrow(X_std), .multioutcome_cvae_model$latent_dim), call. = FALSE)
  }}
  storage.mode(Z) <- "double"

  hidden <- cbind(X_std, Z)
  for (layer in .multioutcome_cvae_model$decoder_layers) {{
    hidden <- pmax(.cvae_add_bias(hidden %*% layer$weight, layer$bias), 0)
  }}
  head <- .multioutcome_cvae_model$head_layers
  core <- pmax(.cvae_add_bias(hidden %*% head[[1L]]$weight, head[[1L]]$bias), 0)
  core <- .cvae_add_bias(core %*% head[[2L]]$weight, head[[2L]]$bias)
  skip <- .cvae_add_bias(
    X_std %*% .multioutcome_cvae_model$skip_layer$weight,
    .multioutcome_cvae_model$skip_layer$bias
  )
  probabilities <- plogis(core + skip)
  colnames(probabilities) <- .multioutcome_cvae_model$outcome_names
  probabilities
}}

cvae_marginal_probabilities <- function(X, n_mc = 20L, seed = NULL,
                                        inference_batch_size = 10000L) {{
  X <- .cvae_validate_x(X)
  n_mc <- as.integer(n_mc)
  inference_batch_size <- as.integer(inference_batch_size)
  if (length(n_mc) != 1L || is.na(n_mc) || n_mc < 1L) stop("n_mc must be positive.", call. = FALSE)
  if (length(inference_batch_size) != 1L || is.na(inference_batch_size) ||
      inference_batch_size < 1L) stop("inference_batch_size must be positive.", call. = FALSE)
  if (!is.null(seed)) set.seed(seed)

  result <- matrix(0, nrow(X), .multioutcome_cvae_model$y_dim)
  for (start in seq.int(1L, nrow(X), by = inference_batch_size)) {{
    rows <- start:min(start + inference_batch_size - 1L, nrow(X))
    accumulator <- matrix(0, length(rows), .multioutcome_cvae_model$y_dim)
    for (draw in seq_len(n_mc)) {{
      Z <- matrix(rnorm(length(rows) * .multioutcome_cvae_model$latent_dim),
                  nrow = length(rows))
      accumulator <- accumulator + cvae_decoder_probabilities(X[rows, , drop = FALSE], Z)
    }}
    result[rows, ] <- accumulator / n_mc
  }}
  colnames(result) <- .multioutcome_cvae_model$outcome_names
  result
}}

cvae_simulate <- function(X, n_samples_per_x = 1L, seed = NULL,
                          inference_batch_size = 10000L) {{
  X <- .cvae_validate_x(X)
  n_samples_per_x <- as.integer(n_samples_per_x)
  inference_batch_size <- as.integer(inference_batch_size)
  if (length(n_samples_per_x) != 1L || is.na(n_samples_per_x) || n_samples_per_x < 1L) {{
    stop("n_samples_per_x must be positive.", call. = FALSE)
  }}
  if (length(inference_batch_size) != 1L || is.na(inference_batch_size) ||
      inference_batch_size < 1L) stop("inference_batch_size must be positive.", call. = FALSE)
  if (!is.null(seed)) set.seed(seed)

  if (n_samples_per_x == 1L) {{
    result <- matrix(0L, nrow(X), .multioutcome_cvae_model$y_dim)
  }} else {{
    result <- array(0L, dim = c(nrow(X), n_samples_per_x,
                                .multioutcome_cvae_model$y_dim))
  }}

  for (start in seq.int(1L, nrow(X), by = inference_batch_size)) {{
    rows <- start:min(start + inference_batch_size - 1L, nrow(X))
    X_rep <- X[rep(rows, each = n_samples_per_x), , drop = FALSE]
    Z <- matrix(rnorm(nrow(X_rep) * .multioutcome_cvae_model$latent_dim),
                nrow = nrow(X_rep))
    probabilities <- cvae_decoder_probabilities(X_rep, Z)
    draws <- matrix(rbinom(length(probabilities), 1L, as.vector(probabilities)),
                    nrow = nrow(probabilities), ncol = ncol(probabilities))
    if (n_samples_per_x == 1L) {{
      result[rows, ] <- draws
    }} else {{
      chunk <- aperm(array(t(draws),
                           dim = c(.multioutcome_cvae_model$y_dim,
                                   n_samples_per_x, length(rows))),
                     c(3L, 2L, 1L))
      result[rows, , ] <- chunk
    }}
  }}
  if (n_samples_per_x == 1L) colnames(result) <- .multioutcome_cvae_model$outcome_names
  result
}}
'''

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8")
    return output_path